JFLAGS = -g
JC = javac
#
.SUFFIXES: .java .class
.java.class:
        $(JC) $(JFLAGS) $*.java
CLASSES = Array.java \
default: 
        Array.java
        
classes: $(CLASSES:.java=.class)
clean:
        del Array.class